[logger.db]
uri = "localhost"
port = 3001
username = "admin"
password = "admin"
collection_name = "simdata"

[simulation]
width = 50
height = 40
grid_size = 9
time_delta = 0.01
num_steps = 10000
static_entity_spawn_rate = 1
static_entity_spawn_interval = 3
static_entity_max = 500

# TODO Add some values for entity reference values.
[evolution]
mutability = 0.1
max_children = 8

[entities]
hunger_speed_multiplier = 0.001 # Maximum hunger used by moving.
short_term_memory_span = 3.0
long_term_memory_span = 5.0
prey_saturation = 0.4 # Amount of hunger lost when a prey has been eaten.

[species.bear]
id = 0
prey = [1]
can_move = true
can_see = true
start_amount = 20

[species.deer]
id = 1
prey = [2]
can_move = true
can_see = true
start_amount = 100

[species.plant]
id = 2
prey = []
can_move = false
can_see = false
start_amount = 500