version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: simDB
    command: mongod --port 3001
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "3001:3001"
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  web:
    build:
      context: ./web/
      target: runner
    volumes:
      - ./web:/web
    command: npm run dev
    container_name: Web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
networks:
  MONGO:
    name: MONGO

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG